SELECT
    c.ID
FROM (
    SELECT ID,PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL) a
    INNER JOIN ECOLI_DATA b ON a.ID = b.PARENT_ID 
    INNER JOIN ECOLI_DATA c ON b.ID = c.PARENT_ID
ORDER BY
    c.ID ASC;