WITH CAR_INFO AS (
    SELECT CAR.CAR_ID,
           CAR.CAR_TYPE,
           CAR.DAILY_FEE,
           DIS.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR AS CAR
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DIS
    ON(CAR.CAR_TYPE = DIS.CAR_TYPE)
    WHERE DIS.DURATION_TYPE IN('30일 이상') AND CAR.CAR_TYPE IN('세단', 'SUV')
)
                         
SELECT CAR_ID, CAR_TYPE, ROUND((1 - DISCOUNT_RATE / 100) * DAILY_FEE * 30) AS FEE
FROM CAR_INFO
WHERE CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01')
)
AND (1 - DISCOUNT_RATE / 100) * DAILY_FEE * 30 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC