WITH T AS (
    SELECT ID, 
           ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RNK,
           COUNT(*) OVER() AS TOTAL_COUNT
    FROM ECOLI_DATA
)

SELECT ID,
       CASE WHEN RNK <= (TOTAL_COUNT * 0.25) THEN 'CRITICAL'
            WHEN RNK <= (TOTAL_COUNT * 0.5) THEN 'HIGH'
            WHEN RNK <= (TOTAL_COUNT * 0.75) THEN 'MEDIUM'
            ELSE 'LOW'
       END AS COLONY_NAME
FROM T
ORDER BY ID