WITH T AS (
    SELECT *,
           IF(START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16', 1, 0) AS ISRENTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    
)

SELECT CAR_ID,
       IF(SUM(ISRENTAL) > 0, '대여중', '대여 가능') AS AVAILABILITY
FROM T
GROUP BY CAR_ID
ORDER BY CAR_ID DESC