WITH TOTAL AS (
    SELECT J.SHIPMENT_ID,
           J.FLAVOR,
           (IFNULL(H.TOTAL_ORDER, 0) + J.TOTAL_ORDER) AS SUM_ORDER
    FROM JULY J LEFT OUTER JOIN FIRST_HALF H
    ON J.SHIPMENT_ID = H.SHIPMENT_ID
)

SELECT FLAVOR
FROM TOTAL
GROUP BY FLAVOR
ORDER BY SUM(SUM_ORDER) DESC
LIMIT 3