SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE NATURAL JOIN REST_REVIEW
WHERE MEMBER_ID = (
                    SELECT MEMBER_ID
                    FROM MEMBER_PROFILE NATURAL JOIN REST_REVIEW
                    GROUP BY (MEMBER_ID)
                    ORDER BY COUNT(*) DESC
                    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT