SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD
LEFT OUTER JOIN ECOLI_DATA AS PARENT
ON(PARENT.ID = CHILD.PARENT_ID)
WHERE CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC