SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE
                    FROM SKILLCODES
                    WHERE NAME IN ('C#')) > 0
OR
SKILL_CODE & (SELECT CODE
              FROM SKILLCODES
              WHERE NAME IN('Python')) > 0
ORDER BY ID ASC