WITH T AS (SELECT *,
           MAX(LENGTH) OVER(PARTITION BY FISH_TYPE) AS MAX_LENGTH
           FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO)

SELECT ID, FISH_NAME, LENGTH
FROM T
WHERE LENGTH = MAX_LENGTH
ORDER BY ID ASC